import img1 from './photo/prof1.png'
import img2 from './photo/prof2.png'
import img3 from './photo/prof3.png'

export const test =[
    {   id:1,
        name: 'Sebastian',
        profession: 'Graphic design',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img1,
        alt:'images_photo',
        star:5,
        
    },
    {   id:2,
        name: 'Evangeline',
        profession: 'Model',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img2,
        alt:'images_photo',
        star:5,
    },
    {   id:3,
        name: 'Alexander',
        profession: 'Software engineer',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img3,
        alt:'images_photo',
        star:4,
    },

    {   id:4,
        name: 'Mona',
        profession: 'Designer',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img2,
        alt:'images_photo',
        star:5,
    },
    {   id:5,
        name: 'Motty',
        profession: 'Graphic design',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img3,
        alt:'images_photo',
        star:3,
    },
    {   id:6,
        name: 'Sebastian',
        profession: 'Graphic design',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img1,
        alt:'images_photo',
        star:5,
    },
    {   id:7,
        name: 'Kolya',
        profession: 'Graphic design',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img3,
        alt:'images_photo',
        star:3,
    },
    {   id:8,
        name: 'Sveta',
        profession: 'Graphic design',
        text: 'Lorem Ipsum is simply dummy text of the printing and typeset industry. Lorem Ipsum has been lorem ...',
        imag:img2,
        alt:'images_photo',
        star:1,
    }
]